main_enlace:
    resource: "@MainBundle/Resources/config/routing/enlace.yml"
    prefix:   /enlace

main_imagen:
    resource: "@MainBundle/Resources/config/routing/imagen.yml"
    prefix:   /imagen

main_video:
    resource: "@MainBundle/Resources/config/routing/video.yml"
    prefix:   /video    

main_categoria:
    resource: "@MainBundle/Resources/config/routing/categoria.yml"
    prefix:   /categoria

main_localidad:
    resource: "@MainBundle/Resources/config/routing/localidad.yml"
    prefix:   /localidad

main_homepage:
    resource: "@MainBundle/Resources/config/routing/puntodeinteres.yml"
    prefix:   /    