main_enlace:
    resource: "@MainBundle/Resources/config/routing/enlace.yml"
    prefix:   /enlaces

main_imagen:
    resource: "@MainBundle/Resources/config/routing/imagen.yml"
    prefix:   /imagenes

main_video:
    resource: "@MainBundle/Resources/config/routing/video.yml"
    prefix:   /videos    

main_categoria:
    resource: "@MainBundle/Resources/config/routing/categoria.yml"
    prefix:   /categorias

main_localidad:
    resource: "@MainBundle/Resources/config/routing/localidad.yml"
    prefix:   /localidades

main_homepage:
    resource: "@MainBundle/Resources/config/routing/puntodeinteres.yml"
    prefix:   /    